apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - namespace.yaml
  - service.yaml
  - prometheus-configmap.yaml
  - prometheus-rbac.yaml
  - ne-daemonset.yaml
  - ne-service.yaml
  - ne-rbac.yaml