apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: busybox-flux
  name: busybox-flux
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: busybox-flux
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '80'
      labels:
        app: busybox-flux
    spec:
      containers:
      - image: busybox:1.28
        imagePullPolicy: IfNotPresent
        name: busybox
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 50m
            memory: 64Mi
        command:
          - sleep
          - "3000"