apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-frontend
  namespace: gitops-portal
  labels:
    app: portal-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portal-frontend
  template:
    metadata:
      labels:
        app: portal-frontend
    spec:
      imagePullSecrets:
      - name: ghcr-pull-secret
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        runAsGroup: 101
      containers:
      - name: frontend
        image: ghcr.io/antoguaro10/portal-frontend:1.0
        ports:
        - containerPort: 8080
          name: http
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
        resources:
          limits:
            cpu: 200m
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: gitops-portal
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '8080'
spec:
  type: LoadBalancer 
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: portal-frontend