apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-frontend
  namespace: gitops-portal
  labels:
    app: portal-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portal-frontend
  template:
    metadata:
      labels:
        app: portal-frontend
    spec:
      imagePullSecrets:
      - name: ghcr-pull-secret
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        runAsGroup: 101
      containers:
      - name: frontend
        image: ghcr.io/antoguaro10/portal-frontend:2.0
        ports:
        - containerPort: 8080
          name: http
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: portal-frontend-nginx-config
          mountPath: /etc/nginx/conf.d/
          readOnly: true
        resources:
          limits:
            cpu: 200m
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 128Mi
      volumes:
        - name: portal-frontend-nginx-config
          configMap:
            name: portal-frontend-nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: gitops-portal
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '8080'
spec:
  type: LoadBalancer 
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: portal-frontend
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: portal-frontend-nginx-config
  namespace: gitops-portal
data:
  default.conf: |
    server {
        listen 8080;
        server_name localhost;

        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html;
        }

        location /api/ {
            proxy_pass http://portal-backend.gitops-portal.svc.cluster.local:8080/api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }